GET http://localhost:3001/routes-list


###
GET http://localhost:3001/api/cart

###
GET http://localhost:3001/api/cart/44

###
DELETE http://localhost:3001/api/cart/44

###
POST http://localhost:3001/api/cart
Content-Type: application/json

{
    "cart": "cart1234",
    "answer": "password",
    "img": "http"
}


###

###
PUT http://localhost:3001/api/cart/8
Content-Type: application/json

{
    "text": "Nhi Đã Thay Đổi",
    "status": "VinhYeuNhi@example.com",
    "index": 2
}

