###
GET http://localhost:3001/api/image?page=&pageSize=5

###
GET http://localhost:3001/api/image/14

###
DELETE http://localhost:3001/api/image/14

###
POST http://localhost:3001/api/image/product/100017
Content-Type: application/json

{
    "imgIds": [
        171,170
    ]
}


###

###
PUT http://localhost:3001/api/image/2
Content-Type: application/json

{
    "fullname": "Nhi Đã Thay Đổi",
    "email": "VinhYeuNhi@example.com",
    "phone": "0123456"
}

