###
GET http://localhost:3001/api/image?page=&pageSize=5


###
### đây là form đổi images của Product!
POST http://localhost:3001/api/image/product/100017
Content-Type: application/json

{
    "imgIds": [
        171,170
    ]
}


###
### 
POST http://localhost:3001/api/image/slider
Content-Type: application/json

{
    "imgIds": [
        171,170
    ]
}

