GET http://localhost:3001/routes-list


###
GET http://localhost:3001/api/user/all?page=4&pageSize=5

###
GET http://localhost:3001/api/user/14

###
DELETE http://localhost:3001/api/user/14

###
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username": "user1234",
    "password": "password",
    "fullname": "User Full Name",
    "email": "VinhYeuNhi@example.com",
    "avt": "https://example.avt.com"
}


###

###
PUT http://localhost:3001/api/user/2
Content-Type: application/json

{
    "fullname": "Nhi Đã Thay Đổi",
    "email": "VinhYeuNhi@example.com",
    "phone": "0123456"
}

